name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK using Web2APK
        uses: 77AXEL/Web2APK@v1.0
        with:
          app-name: "SmartTasks"
          url: "https://yebanada.github.io/Smart-task/"
          icon: "" # Leave empty for default icon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartTasks-APK
          path: ./*.apk
